# Generated by Django 4.2.4 on 2023-08-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=511)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.block'),
        ),
    ]
