# Generated by Django 4.2.4 on 2023-08-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_block_alter_question_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='block',
            name='number',
            field=models.IntegerField(),
        ),
    ]
