# Generated by Django 4.2.4 on 2023-11-19 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_block_title_alter_block_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.IntegerField(choices=[(0, 'strongly agree'), (1, 'agree'), (2, 'disagree'), (3, 'strongly disagree'), (4, 'unavailable')], default=0),
        ),
    ]
