name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Install dos2unix
      run: sudo apt-get install dos2unix
    - name: Build and push Docker images
      run: |
        docker build -t allyellow/aimb .
        docker push allyellow/aimb
    - name: List Files
      run: ls -ltrh
